name = "ExtremeTracking"
uuid = "a17244fd-460c-4c40-9010-a8037b15ab47"
authors = ["ZijieZhaoMMHW <zijiezhaomj@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
